Removed function get_magic_quotes_gpc()
This function has been DEPRECATED as of PHP 7.4.0, and REMOVED as of PHP 8.0.0

Fixes this error:
Fatal error: Uncaught Error: Call to undefined function get_magic_quotes_gpc()